### PR TITLE
[Fix] Validate integers before encoding.

### PR DESCRIPTION
**Pull request by ruseinov**
Closes: https://github.com/ipld/serde_ipld_dagcbor/issues/14

This is breaking on of the tests in `std_types.rs`. I'm not sure what the purpose of that test is, should it be modified or removed?

### CODE REVIEW

**Comment by vmx** [comment]
When I try locally all tests pass. The CI failures are due to code style.

**Comment by ruseinov** [comment]
> When I try locally all tests pass. The CI failures are due to code style.

```
     Running tests/std_types.rs (target/debug/deps/std_types-5e411f9cb0297c90)

running 25 tests
test test_bool_true ... ok
test test_bool_false ... ok
test test_char_broken_heart ... ok
test test_char_null ... ok
test test_color_enum ... ok
test test_color_enum_transparent ... ok
test test_color_enum_with_alpha ... ok
test test_f64_12345_point_6 ... ok
test test_i128_a ... ok
test test_i8_23 ... ok
test test_i8_24 ... ok
test test_i8_5 ... ok
test test_i8_neg_128 ... ok
test test_isize_255 ... ok
test test_isize_neg_256 ... ok
test test_isize_neg_257 ... ok
test test_newtype_struct ... ok
test test_option_none ... ok
test test_option_some ... ok
test test_optional_person_struct ... ok
test test_i128_b ... FAILED
test test_person_struct ... ok
test test_str_pangram_de ... ok
test test_u128 ... ok
test test_u32_98745874 ... ok
```
One of the tests is using `i128::MIN` so it should not pass, given we validate it now.

**Comment by ruseinov** [comment]
Yep, still failing. It's a fairly easy fix, either removing the test or changing it's value to a `-u64::MAX`. I'm kind of hesitant to do it, because it isn't clear what the purpose of this test was to begin with.

**Comment by vmx** [comment]
> because it isn't clear what the purpose of this test was to begin with.

Historic reasons, they are inherited from an old code base.

**Comment by ruseinov** [comment]
> > When I try locally all tests pass. The
> 
> I did run the wrong branch ;)
> 
> I've seen that you've already added tests for `i128` and `u128` for number that are within the =/-`u64` range. So I think that's good enough. Just remove the failing test in `std_types`.

Roger that!

**Comment by ruseinov** [comment]
It's done, should be good now.

**Review by vmx — APPROVED** [review]
Thanks a lot for the bug report and the fix. I'll leave it open for a bit, so that others can chime in in case they see a problem (though I wouldn't expect that there are any).

**Comment by ruseinov** [comment]
> Thanks a lot for the bug report and the fix. I'll leave it open for a bit, so that others can chime in in case they see a problem (though I wouldn't expect that there are any).

You are very welcome. I'm glad that this went swift and smooth, thanks a lot for all the context.

**Pull request merged**
